const coffeeItems = [
  {
    id: 1,
    name: "Espresso",
    price: "$3.00",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "A full-flavored, concentrated form of coffee.",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Latte",
    price: "$4.00",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "A creamy blend of espresso and steamed milk.",
    rating: 4.7,
  },
  {
    id: 3,
    name: "Cappuccino",
    price: "$4.50",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "A perfect balance of espresso, steamed milk, and foam.",
    rating: 4.9,
  },
  {
    id: 4,
    name: "Mocha",
    price: "$4.75",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "A chocolate-flavored variant of a caffè latte.",
    rating: 4.6,
  },
  {
    id: 5,
    name: "Macchiato",
    price: "$3.50",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "Espresso with a small amount of foamed milk.",
    rating: 4.5,
  },
  {
    id: 6,
    name: "Americano",
    price: "$2.50",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "Espresso with added hot water.",
    rating: 4.3,
  },
  {
    id: 7,
    name: "Flat White",
    price: "$4.00",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "Espresso with steamed milk and microfoam.",
    rating: 4.7,
  },
  {
    id: 8,
    name: "Affogato",
    price: "$5.00",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2XAM3Q0BdOugQuQtuHh1OpshRP435xKIANI5AubXAw&s",
    description: "Espresso poured over a scoop of vanilla ice cream.",
    rating: 4.9,
  },
  {
    id: 9,
    name: "Café au Lait",
    price: "$3.75",
    imageUrl: "https://example.com/cafeaulait.jpg",
    description: "Brewed coffee with steamed milk.",
    rating: 4.4,
  },
  {
    id: 10,
    name: "Irish Coffee",
    price: "$6.00",
    imageUrl: "https://example.com/irishcoffee.jpg",
    description: "Coffee with Irish whiskey, sugar, and cream.",
    rating: 4.8,
  },
  {
    id: 11,
    name: "Turkish Coffee",
    price: "$4.25",
    imageUrl: "https://example.com/turkishcoffee.jpg",
    description: "A traditional Middle Eastern coffee preparation.",
    rating: 4.7,
  },
  {
    id: 12,
    name: "Vienna",
    price: "$4.50",
    imageUrl: "https://example.com/vienna.jpg",
    description: "A blend of espresso, whipped cream, and chocolate.",
    rating: 4.6,
  },
  {
    id: 13,
    name: "Cortado",
    price: "$3.25",
    imageUrl: "https://example.com/cortado.jpg",
    description: "Espresso cut with a small amount of warm milk.",
    rating: 4.5,
  },
  {
    id: 14,
    name: "Ristretto",
    price: "$3.00",
    imageUrl: "https://example.com/ristretto.jpg",
    description: "A shorter, more concentrated espresso shot.",
    rating: 4.8,
  },
  {
    id: 15,
    name: "Doppio",
    price: "$3.50",
    imageUrl: "https://example.com/doppio.jpg",
    description: "A double shot of espresso.",
    rating: 4.7,
  },
  {
    id: 16,
    name: "Lungo",
    price: "$3.75",
    imageUrl: "https://example.com/lungo.jpg",
    description: "An espresso with more water, making it larger.",
    rating: 4.6,
  },
  {
    id: 17,
    name: "Café Con Hielo",
    price: "$3.00",
    imageUrl: "https://example.com/cafeconhielo.jpg",
    description: "Iced coffee with a Spanish twist.",
    rating: 4.3,
  },
  {
    id: 18,
    name: "Café Cubano",
    price: "$3.25",
    imageUrl: "https://example.com/cafecubano.jpg",
    description: "A type of espresso that originated in Cuba.",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Cold Brew",
    price: "$4.00",
    imageUrl: "https://example.com/coldbrew.jpg",
    description: "Coffee brewed slowly with cold water.",
    rating: 4.9,
  },
  {
    id: 20,
    name: "Nitro Coffee",
    price: "$5.00",
    imageUrl: "https://example.com/nitrocoffee.jpg",
    description: "Cold brew coffee infused with nitrogen gas.",
    rating: 4.8,
  },
  {
    id: 21,
    name: "Frappuccino",
    price: "$5.50",
    imageUrl: "https://example.com/frappuccino.jpg",
    description: "A trademarked brand of the Starbucks Corporation.",
    rating: 4.6,
  },
  {
    id: 22,
    name: "Iced Coffee",
    price: "$3.50",
    imageUrl: "https://example.com/icedcoffee.jpg",
    description: "Regular coffee served over ice.",
    rating: 4.3,
  },
  {
    id: 23,
    name: "Café Breve",
    price: "$4.50",
    imageUrl: "https://example.com/cafebreve.jpg",
    description: "Espresso with steamed half-and-half.",
    rating: 4.5,
  },
];

export default coffeeItems;
